# Generated by Django 2.2.2 on 2019-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
